version: '3.4'
services:
  BD:
    image: mariadb
    container_name: shop_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shop
      MYSQL_USER: pepe
      MYSQL_PASSWORD: Pepe@1234
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
